//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APIS_IS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class cheque
    {
        public int pk_id_cheque { get; set; }
        public int fk_id_cuenta_bancaria { get; set; }
        public string correlativo { get; set; }
        public int n_cuenta { get; set; }
        public double monto { get; set; }
        public string descripcion { get; set; }
        public System.DateTime fecha { get; set; }
        public string destinatario { get; set; }
    }
}
