//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APIS_IS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class cuenta_bancaria
    {
        public int pk_id_cuenta_bancaria { get; set; }
        public int fk_id_banco { get; set; }
        public int fk_id_tipo_moneda { get; set; }
        public int fk_id_tipo_cuenta { get; set; }
        public int no_cuenta { get; set; }
        public Nullable<int> fk_id_usuario { get; set; }
    }
}
