//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APIS_IS.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class pruebaEntities1 : DbContext
    {
        public pruebaEntities1()
            : base("name=pruebaEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<banco> banco { get; set; }
        public virtual DbSet<cheque> cheque { get; set; }
        public virtual DbSet<cuenta_bancaria> cuenta_bancaria { get; set; }
        public virtual DbSet<pago_prestamo> pago_prestamo { get; set; }
        public virtual DbSet<pago_servicio> pago_servicio { get; set; }
        public virtual DbSet<pago_tarjeta> pago_tarjeta { get; set; }
        public virtual DbSet<registro> registro { get; set; }
        public virtual DbSet<saldos> saldos { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<tarjeta> tarjeta { get; set; }
        public virtual DbSet<tipo_cuenta> tipo_cuenta { get; set; }
        public virtual DbSet<tipo_modena> tipo_modena { get; set; }
        public virtual DbSet<tipo_servicio> tipo_servicio { get; set; }
        public virtual DbSet<tipo_tarjeta> tipo_tarjeta { get; set; }
        public virtual DbSet<tipo_transferencia> tipo_transferencia { get; set; }
        public virtual DbSet<transferencia> transferencia { get; set; }
        public virtual DbSet<usuario> usuario { get; set; }
    }
}
