//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APIS_IS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class saldos
    {
        public int pk_id_saldo { get; set; }
        public int fk_id_cuenta_bancaria { get; set; }
        public double saldo_disponible { get; set; }
        public double saldo_flotante { get; set; }
        public double salto_total { get; set; }
        public System.DateTime fecha { get; set; }
    }
}
