//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APIS_IS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tarjeta
    {
        public int pk_id_tarjeta { get; set; }
        public int fk_id_tipo_tarjeta { get; set; }
        public string serie { get; set; }
        public string codigo { get; set; }
        public System.DateTime fecha_vencimiento { get; set; }
    }
}
